version: '3.7'

services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    volumes:
    - mysql_data:/var/lib/mysql:rw
    - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    stop_grace_period: 1m
    networks:
      - net_backend
    env_file:
      - .env

  app:
    depends_on:
      - mysql
    image: hsuan.cloud/hsuan/smartclouds-exercise:0.0.1
    # build:
    #   context: ./
    container_name: app
    restart: unless-stopped
    volumes:
      - app_data:/var/www/html
    networks:
      - net_backend

  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: nginx
    volumes:
      - app_data:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - app
    networks:
      - net_frontend
      - net_backend

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080
    networks:
      - net_frontend
      - net_backend

volumes:
  mysql_data:
  app_data:

networks:
  net_frontend:
    name: net_frontend
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
  net_backend:
    name: net_backend
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24
